yalamain/blueprints/assets.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from flask import render_template, request, jsonify
from flask_login import login_required
from sqlalchemy import exc

from yalamain.models import *

assets_bp = Blueprint('assets', __name__)


@assets_bp.route('/host', methods=['GET'])
@login_required
def assets_host():
    """
    :主机管理页面
    """
    if request.method == 'GET':
        return render_template('assets/host.html', menu='host_list')


@assets_bp.route('/host/detail/', methods=['GET'])
@login_required
def assets_host_detail():
    """
    :TODO: 仅仅返回单个主机的详细信息，没必要使用分页。后续修改.
    """
    try:
        host_id = request.args.get('host_id')
        page = request.args.get('page', 1, type=int)
        pagination = Host.query.filter_by(id=host_id).paginate(page, per_page=current_app.config['PER_PAGE'],
                                                               error_out=False)
        hosts = pagination.items
        return render_template('assets/host_detail.html', hosts=hosts, menu='host_detail', pagination=pagination)
    except Exception as e:
        return jsonify({
            'resCode': -1,
            'errMsg': str(e),
        })


@assets_bp.route('/service', methods=['GET'])
@login_required
def assets_service():
    if request.method == 'GET':
        page = request.args.get('page', 1, type=int)
        try:
            pagination = Service.query.paginate(page, per_page=current_app.config['PER_PAGE'], error_out=False)
            services = pagination.items
        except exc.SQLAlchemyError as sql_err:
            current_app.logger.error(sql_err)
            pagination = None
            services = None
        except Exception as e:
            current_app.logger.error(e)
            pagination = None
            services = None

        return render_template('assets/service.html', services=services, menu='service_list', pagination=pagination)


@assets_bp.route('/department', methods=['GET'])
@login_required
def assets_department():
    if request.method == 'GET':
        page = request.args.get('page', 1, type=int)
        try:
            pagination = Department.query.paginate(page, per_page=current_app.config['PER_PAGE'], error_out=False)
            dpts = pagination.items
        except exc.SQLAlchemyError as sql_err:
            current_app.logger.error(sql_err)
            pagination = None
            dpts = None
        except Exception as e:
            current_app.logger.error(e)
            pagination = None
            dpts = None
        return render_template('assets/department.html', dpts=dpts, menu='department_list', pagination=pagination)


@assets_bp.route('/ip/pool', methods=['GET'])
@login_required
def assets_ip_pool():
    """
    :IP地址池列表页面
    """
    if request.method == 'GET':
        page = request.args.get('page', 1, type=int)
        try:
            pagination = IPSegment.query.paginate(page, per_page=current_app.config['PER_PAGE'], error_out=False)
            ip_segments = pagination.items
        except exc.SQLAlchemyError as sql_err:
            current_app.logger.error(sql_err)
            ip_segments = None
            pagination = None
        except Exception as err:
            current_app.logger.error(err)
            ip_segments = None
            pagination = None
        return render_template('assets/ip_pool.html', ip_segments=ip_segments, menu='ip_pool_list', pagination=pagination)


@assets_bp.route('/ip/pool/detail', methods=['GET'])
@login_required
def asset_ip_pool_detail():
    """
    :查看某IP地址段详细的IP地址列表
    """
    try:
        ip_segment_id = request.args.get('ip_segment_id')
        page = request.args.get('page', 1, type=int)
        page_size = current_app.config['PER_PAGE']
        pagination = IPPool.query.filter_by(ip_segment_id=ip_segment_id).paginate(page, per_page=page_size, error_out=False)
        ip_pools = pagination.items
    except Exception as e:
        return jsonify({
            'result': -1,
            'errMsg': str(e),
        })
    return render_template('assets/ip_pool_detail.html', ippools=ip_pools, ip_segment_id=ip_segment_id,
                           menu='ip_pool_detail_list', pagination=pagination)

yalamain/blueprints/auth.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from flask import render_template, redirect, url_for, request, jsonify, session, current_app
from flask_login import login_user, logout_user, login_required, current_user
import uuid
import re

from yalamain.models import User, Role
from yalamain.extensions import db, ldap

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def auth_login():
    if request.method == 'GET':
        return render_template('auth/login.html')

    if request.method == 'POST':
        username = request.form.get('username', '')
        password = request.form.get('password', '')
        remember_me = request.form.get('remember_me', False)
        next = request.args.get('next', '')
        if username and password:
            try:
                ldap_username = username + '@dadaabc.net'
                # STEP1: 向LDAP查询username和password
                ldap_user = ldap.bind_user(ldap_username, password)
                if ldap_user is None:
                    # STEP2: 认证错误处理
                    current_app.logger.info('{0} login error.'.format(username))
                    return jsonify({
                        'resCode': -1,
                        'errMsg': u'用户没有权限登录系统，请联系AD管理员处理！'
                    })
                else:
                    # STEP3: LDAP认证成功后，通过username查询MySQL
                    user = User.query.filter_by(name=username).first()
                    user_ad_name = ldap.get_object_details(ldap_username).get('cn')[0].decode('utf-8')
                    fullname = re.findall(r'[(](.*?)[)]', user_ad_name)[0] if user_ad_name.find(
                        '(') >= 0 and user_ad_name.find(')') >= 0 else user_ad_name

                    # STEP4: MySQL查询username为空后，插入username数据
                    if user is None:
                        u = User()
                        u.name = username
                        u.fullname = fullname if fullname is not None else None
                        u.password = password
                        u.email = ldap_username
                        u.status = True
                        u.role_id = Role.query.filter_by(name='RD').first().id
                        u.token = str(uuid.uuid3(uuid.NAMESPACE_DNS, ldap_username))
                        db.session.add(u)

                    # STEP5: username信息写入session
                    user = User.query.filter_by(name=username).first()
                    login_user(user, remember_me)
                    session['username'] = username

                    current_app.logger.info('{0} login success.'.format(username))
                    return jsonify({
                        'resCode': 1,
                        'next': next
                    })
            except Exception as e:
                return jsonify({
                    'resCode': -1,
                    'errMsg': str(e),
                })


@auth_bp.route('/logout/')
@login_required
def auth_logout():
    current_app.logger.info('{0} logout.'.format(current_user.name))
    logout_user()
    return redirect(url_for('auth.login'))

yalamain/blueprints/index.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from flask import render_template, send_file, current_app, Markup
from flask_login import login_required
import os
from sqlalchemy import exc
from datetime import datetime, timedelta
import datetime

from yalamain.extensions import ldap
from yalamain.models import MonitorDomainInfo, MonitorTcpConnectProbe
from yalamain.models import Host, User, CronLog

index_bp = Blueprint('index', __name__)


@index_bp.route('/')
@ldap.login_required
def login():
    return render_template('auth/login.html')


@index_bp.route('/index')
@login_required
def index():
    try:
        host_count = Host.query.count()
        monitor_domain_count = MonitorDomainInfo.query.count()
        monitor_probe_count = MonitorTcpConnectProbe.query.count()
        users_count = User.query.count()
    except exc.SQLAlchemyError as sql_err:
        current_app.logger.error(sql_err)
        host_count = 0
        monitor_domain_count = 0
        monitor_probe_count = 0
        users_count = 0

    try:
        chart_list = []
        for i in reversed(range(15)):
            chart_dict = {}
            update_date = (datetime.datetime.now() - datetime.timedelta(days=i))
            update_date = update_date.strftime('%Y-%m-%d')
            cron_logs = CronLog.query.filter(CronLog.update_date == update_date).all()
            for c in cron_logs:
                chart_dict['update_date'] = update_date
                chart_dict[c.asset] = c.count
            if (len(chart_dict)) == 5:
                chart_list.append(chart_dict)
    except exc.SQLAlchemyError as sql_err:
        chart_list = []

    return render_template('index.html', menu='dashboard', host_count=host_count, monitor_domain_count=monitor_domain_count,
                           monitor_probe_count=monitor_probe_count, users_count=users_count,
                           chart_list=Markup(chart_list))


@index_bp.route('/changeLog')
@login_required
def changelog():
    return render_template('changelog.html')


@index_bp.route('/ChangeLog.md')
@login_required
def get_changelog_md():
    base_dir = os.path.abspath(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
    return send_file(os.path.join(base_dir, 'ChangeLog.md'))

yalamain/blueprints/user.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from flask import render_template, redirect, url_for, request, jsonify, current_app
from flask_login import login_required
from sqlalchemy import exc, or_, exists, not_
import uuid
import json

from yalamain.models import User, Role, Permission, role_permission
from yalamain.extensions import db

user_bp = Blueprint('user', __name__)


@user_bp.route('/user', methods=['GET', 'POST'])
@login_required
def user_user():
    if request.method == 'GET':
        page = request.args.get('page', 1, type=int)
        search = ''
        try:
            pagination = User.query.paginate(page, per_page=current_app.config['PER_PAGE'], error_out=False)
            users = pagination.items
        except exc.SQLAlchemyError as sql_err:
            current_app.logger.error(sql_err)
            users = None
            pagination = None
        except Exception as e:
            current_app.logger.error(e)
            users = None
            pagination = None
        return render_template('user/users.html', users=users, search=search, menu='user_list', pagination=pagination)

    if request.method == 'POST':
        search = request.form.get('search', '')

        if not search:
            return redirect(url_for('user.user_user'))

        try:
            users = User.query.filter(
                or_(User.name.like('%' + search + '%'),
                    User.fullname.like('%' + search + '%'),
                    exists().where(Role.id == User.role_id).where(Role.name.like('%' + search + '%')),
                    User.email.like('%' + search + '%'))).all()
        except exc.SQLAlchemyError as sql_err:
            current_app.logger.error(sql_err)
            users = None
            pagination = None
        except Exception as e:
            current_app.logger.error(e)
            users = None
            pagination = None
        return render_template('user/users.html', users=users, search=search, menu='user_list')


@user_bp.route('/role', methods=['GET'])
@login_required
def user_role():
    if request.method == 'GET':
        page = request.args.get('page', 1, type=int)
        page_size = current_app.config['PER_PAGE']
        try:
            pagination = Role.query.paginate(page, per_page=page_size, error_out=False)
            roles = pagination.items
        except exc.SQLAlchemyError as sql_err:
            current_app.logger.error(sql_err)
            roles = None
            pagination = None
        except Exception as e:
            current_app.logger.error(e)
            roles = None
            pagination = None
        return render_template('user/roles.html', roles=roles, menu='role_list', pagination=pagination)


@user_bp.route('/permission', methods=['GET'])
@login_required
def user_permission():
    if request.method == 'GET':
        page = request.args.get('page', 1, type=int)
        page_size = current_app.config['PER_PAGE']
        try:
            pagination = Permission.query.paginate(page, per_page=page_size, error_out=False)
            permissions = pagination.items
        except exc.SQLAlchemyError as sql_err:
            current_app.logger.error(sql_err)
            permissions = None
            pagination = None
        except Exception as e:
            current_app.logger.error(e)
            permissions = None
            pagination = None
        return render_template('user/permission.html', permissions=permissions, menu='permission_list', pagination=pagination)

yalamain/templates/changelog.html
{% extends "base.html" %}
{% import "page.html" as page %}
{% block content %}
    <div id="building" class="content-wrapper list">
        <section class="content-header">
            <p style="font-size: xx-large">
                ChangeLog
            </p>
        </section>
        <section class="content">
            <div class="row" align="left" v-for="log in changelog" style="margin-top: 20px; margin-left: 15px;">
                <div style="border-bottom: 1px solid #ccc; width: 60%; height: auto; padding-bottom: 20px;">
                    <h2>
                    [[ log.version ]]
                    </h2>
                    <p  v-for = "detailItem in log.details">[[ detailItem ]]</p>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

{% block bottom_js %}
    <script>
        dataLog = {
            errMsg: '',
            changelog: [],
        };
        Vue.config.delimiters = ['[[', ']]'];
        window.onload = function () {
            $.ajax({
                   url : "ChangeLog.md",
                   dataType: "text",
                   success : function (data) {
                       console.log(data);
                       let logs = data.split('##');
                       for (let i = logs.length - 1; i > 0; i--) {
                           let log1 = logs[i];
                           if (log1 !== "") {
                               let logArray = log1.split('\n');
                               let logDetails1 = [];
                               for (let j = 1; j < logArray.length; j++) {
                                   if (logArray[j] !== "") {
                                       logDetails1.push(logArray[j]);
                                   }
                               }
                                   let logDetails = {
                                       "version": logArray[0],
                                       "details": logDetails1,
                                   };
                                   dataLog.changelog.push(logDetails);
                               }
                           }
                       }
                   });
            $(document).ready(function() {

            });
        };

        new Vue({
            el: '.list',
            data: dataLog,
            methods: {}
        })
    </script>
{% endblock %}

yalamain/templates/footer.html
<footer class="main-footer">
    <strong> YALA &nbsp; &nbsp; &nbsp; Version 1.0.0 </strong> &nbsp; &nbsp; &nbsp;
    <a href="{{ url_for('index.changelog') }}" > ChangeLog </a>
</footer>

yalamain/templates/index.html
{% extends "base.html" %}
{% import "page.html" as page %}
{% block content %}
    <div id="index" class="content-wrapper list">
        <section class="content-header">
            <h1>
                首页
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-sm-3">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <span class="label label-success pull-right">Hosts</span>
                            <h5>主机总数</h5>
                        </div>
                        <div class="ibox-content">
                            <h1 class="no-margins"><a a href="{{ url_for('assets.assets_host') }}">{{ host_count }}</a></h1>
                            <small>All hosts</small>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <span class="label label-info pull-right">Domain</span>
                            <h5>监控域名管理</h5>
                        </div>
                        <div class="ibox-content">
                            <h1 class="no-margins"><a href="{{ url_for('monitor.monitor_domain') }}">{{ monitor_domain_count }} </a></h1>
                            <small>Monitor domain</small>
                        </div>
                    </div>
                </div>
        
                <div class="col-sm-3">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <span class="label label-primary pull-right">Probe</span>
                            <h5>监控端口管理</h5>
                        </div>
                        <div class="ibox-content">
                            <h1 class="no-margins"><a href="{{ url_for('monitor.monitor_tcp_connect_probe') }}">{{  monitor_probe_count  }}</a></h1>
                            <small>Monitor count</small>
                        </div>
                    </div>
                </div>
        
                <div class="col-sm-3">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <span class="label label-danger pull-right">Users</span>
                            <h5>用户管理</h5>
                        </div>
                        <div class="ibox-content">
                                <h1 class="no-margins"><a href="{{ url_for('user.user_user') }}"> <span id="users_count"></span>{{  users_count  }}</a></h1>
                            <small>All users</small>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="box box-info">
                        <div class="box-header with-border">
                            <h3 class="box-title"> 数据趋势图 </h3>

                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                                </button>
                                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div>
                        <div class="box-body chart-responsive">
                            <div class="chart" id="line-chart" style="height: 300px;"></div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                </div>
            </div>

        </section>
    </div>
{% endblock %}

{% block bottom_js %}
    <script>
        $(function () {
            let line = new Morris.Line({
                element: 'line-chart',
                resize: true,              
                data: {{ chart_list }},
                xkey: 'update_date',
                ykeys: ['host', 'domain', 'probe', 'users'],
                labels: ['host', 'domain', 'probe', 'users'],
                lineColors: ['#3c8dbc', '#00a65a', '#22b882', '#03365a'],
                xlabels: 'day',                
                hideHover: 'auto',
                gridTextSize: 12, // 设置横坐标字体大小，再大最后一格就显示不出来了
                xLabelFormat: function (update_date) {
                     return update_date.getMonth()+'-'+update_date.getDate();
                },
                /*设置横坐标显示格式为月-日*/
            });
        });

        window.onload = function () {

        };

        data = {
            errMsg: '',
        };

        new Vue({
            el: '.list',
            data: data,
            methods: {}
        })
    </script>

{% endblock %}

yalamain/templates/main-header.html
<header class="main-header">
    <a href="{{ url_for('index.index') }}" class="logo">
        <span class="logo-mini">Yala</span>
        <span class="logo-lg"><b>Yala-运维平台</b></span>
    </a>
    <nav class="navbar navbar-static-top" id="navbar_user">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {% if current_user.is_authenticated %}
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            {% if current_user.role.name == 'Admin' %}
                                <img src="{{ url_for('static', filename='image/avatar3.png') }}" class="user-image" alt="User Image">
                            {% elif current_user.role.name == 'Ops' %}
                                <img src="{{ url_for('static', filename='image/avatar2.png') }}" class="user-image" alt="User Image">
                            {% else %}
                                <img src="{{ url_for('static', filename='image/avatar1.png') }}" class="user-image" alt="User Image">
                            {% endif %}
                            <span class="hidden-xs">{{ current_user.name }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header">
                                {% if current_user.role.name == 'Admin' %}
                                    <img src="{{ url_for('static', filename='image/avatar3.png') }}" class="img-circle" alt="User Image">
                                {% elif current_user.role.name == 'Ops' %}
                                    <img src="{{ url_for('static', filename='image/avatar2.png') }}" class="img-circle" alt="User Image">
                                {% else %}
                                    <img src="{{ url_for('static', filename='image/avatar1.png') }}" class="img-circle" alt="User Image">
                                {% endif %}
                                <p>
                                    {{ current_user.name }} - {{ current_user.role.name }}
                                </p>
                            </li>
                            <li class="user-footer">
                                <div class="pull-left">
                                    <span> <p style="font-size: 14px"> 密码修改请到LDAP系统 </p> </span>
                                </div>
                                <div class="pull-right"><a href="{{ url_for('auth.auth_logout') }}" class="btn btn-default btn-flat">退出</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{{ url_for('auth.auth_login') }}">登录</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

yalamain/templates/main-sidebar.html
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                {% if current_user.role.name == 'Admin' %}
                    <img src="{{ url_for('static', filename='image/avatar3.png') }}" class="img-circle" alt="User Image">
                {% elif current_user.role.name == 'Ops' %}
                    <img src="{{ url_for('static', filename='image/avatar2.png') }}" class="img-circle" alt="User Image">
                {% else %}
                    <img src="{{ url_for('static', filename='image/avatar1.png') }}" class="img-circle" alt="User Image">
                {% endif %}
            </div>
            <div class="pull-left info">
                <p>{{ current_user.name }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <ul class="sidebar-menu" data-widget="tree">
            <li id="dashboard">
                <a href="{{ url_for('index.index') }}">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>
            <li class="treeview" id="host_manage">
                <a href="#">
                    <i class="fa fa-tv"></i>
                    <span> 主机管理 </span>
                    <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                </a>
                <ul class="treeview-menu">
                    <li id="host_list" {% if menu == 'host_list' %} class="active" {% endif %}>
                        <a href="{{ url_for('assets.assets_host') }}" style="font-size: 13px"><i class="fa fa-minus-square"></i> 主机信息</a>
                    </li>
                </ul>
            </li>

            <li class="treeview" id="monitor">
                <a href="#">
                    <i class="fa fa-gears"></i>
                    <span> 监控管理 </span>
                    <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                </a>
                <ul class="treeview-menu">
                    <li id="monitor_domain" {% if menu == 'monitor_domain' %} class="active" {% endif %}>
                        <a href="{{ url_for('monitor.monitor_domain') }}" style="font-size: 13px"><i class="fa fa-minus-square"></i> 监控域名管理 </a>
                    </li>
                    <li id="monitor_tcp_connect_probe" {% if menu == 'monitor_tcp_connect_probe' %} class="active" {% endif %}>
                        <a href="{{ url_for('monitor.monitor_tcp_connect_probe') }}" style="font-size: 13px"><i class="fa fa-minus-square"></i> 服务端口监控
                        </a>
                    </li>
                </ul>
            </li>

            {% if current_user.role.name == 'Admin' %}
                <li class="treeview" id="asset_manage">
                    <a href="#">
                        <i class="fa fa-bell-o"></i>
                        <span>管理员配置</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li id="ip_pool" {% if menu == 'ip_pool_list' %} class="active" {% endif %}>
                            <a href="{{ url_for('assets.assets_ip_pool') }}" style="font-size: 13px"><i class="fa fa-minus-square"></i> IP地址池管理</a>
                        </li>
                        <li id="ip_pool" {% if menu == 'service_list' %} class="active" {% endif %}>
                            <a href="{{ url_for('assets.assets_service') }}" style="font-size: 13px"><i class="fa fa-minus-square"></i>
                                服务管理</a>
                        </li>
                        <li id="ip_pool" {% if menu == 'department_list' %} class="active" {% endif %}>
                            <a href="{{ url_for('assets.assets_department') }}" style="font-size: 13px"><i class="fa fa-minus-square"></i> 部门管理</a>
                        </li>
                    </ul>
                </li>
            {% endif %}

            {% if current_user.role.name in ['Admin', 'Ops'] %}
                <li class="treeview" id="permission_manage">
                    <a href="#">
                        <i class="fa fa-user-circle"></i>
                        <span>用户权限管理</span>
                        <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                       <li {% if menu == 'role_list' %} class="active" {% endif %}>
                            <a href="{{ url_for('user.user_role') }}" style="font-size: 13px"><i class="fa fa-minus-square"></i> 角色管理</a>
                        </li>
                        <li {% if menu == 'user_list' %} class="active" {% endif %}>
                            <a href="{{ url_for('user.user_user') }}" style="font-size: 13px"><i class="fa fa-minus-square"></i> 用户管理</a>
                        </li>
                        <li {% if menu == 'permission_list' %} class="active" {% endif %}>
                            <a href="{{ url_for('user.user_permission') }}" style="font-size: 13px"><i class="fa fa-minus-square"></i> 权限列表</a>
                        </li>
                    </ul>
                </li>
            {% endif %}
        </ul>
    </section>
</aside>

yalamain/templates/page.html
{% macro pagination_widget(pagination, endpoint) %}
    <ul class="pagination">
        <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
            <a href="
                    {% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{% else %}#{% endif %}">
                &laquo;
            </a>
        </li>
        {% for p in pagination.iter_pages() %}
            {% if p %}
                {% if p == pagination.page %}
                    <li class="active">
                        <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="disabled"><a href="#">&hellip;</a></li>
            {% endif %}
        {% endfor %}
        <li{% if not pagination.has_next %} class="disabled"{% endif %}>
            <a href="
                    {% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{% else %}#{% endif %}">
                &raquo;
            </a>
        </li>
    </ul>
{% endmacro %}